name: tests for lifebit-ai/phenowrangle
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  plink_binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
        continuous_var_aggregation: [median, min, max, median]
        continuous_var_transformation: [log, log10, log2, zscores, None]
        design_mode: ['case_vs_control_contrast']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Binary plink
        run: |
          nextflow run ${GITHUB_WORKSPACE} --design_mode ${{ matrix.design_mode }} --continuous_var_transformation ${{ matrix.continuous_var_transformation }}  --continuous_var_aggregation ${{ matrix.continuous_var_aggregation }} -profile plink_binary
  plink_qt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
        query: ['None', 's3://marcos-lifebit/phenowrangle/query.json']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Quantitative plink
        run: |
          nextflow run ${GITHUB_WORKSPACE} --query ${{ matrix.query }} -profile plink_qt
  plink_phewas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
        continuous_var_aggregation: [median]
        continuous_var_transformation: [None]
        query: ['None', 's3://marcos-lifebit/phenowrangle/query.json']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: general test for plink_phewas
        run: |
          nextflow run ${GITHUB_WORKSPACE} --query ${{ matrix.query }} --continuous_var_transformation ${{ matrix.continuous_var_transformation }}  --continuous_var_aggregation ${{ matrix.continuous_var_aggregation }} -profile plink_phewas
  